services:
  classroom-reservation-api:
    container_name: classroom-reservation-api
    build: .
    restart: unless-stopped
    depends_on:
      - classroom-reservation-db
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_SMTP_AUTH: ${MAIL_SMTP_AUTH}
      MAIL_SMTP_STARTTLS: ${MAIL_SMTP_STARTTLS}
    ports:
      - "8080:8080"

  classroom-reservation-db:
    container_name: classroom-reservation-db
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - classroom_reservation_db_data:/var/lib/postgresql/data

volumes:
  classroom_reservation_db_data:
